name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check formatting
        working-directory: backend
        run: cargo fmt -- --check

      - name: Run clippy
        working-directory: backend
        run: cargo clippy -- -D warnings 