name: Frontend Code Quality Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  frontend-check:
    name: Frontend Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: my-link-uploader/package-lock.json

      - name: Install Dependencies
        working-directory: ./my-link-uploader
        run: npm ci

      - name: Type Check
        working-directory: ./my-link-uploader
        run: npm run typecheck || npx tsc --noEmit

      - name: ESLint Check
        working-directory: ./my-link-uploader
        run: npm run lint || npx eslint . --ext .ts,.tsx

      - name: Build Check
        working-directory: ./my-link-uploader
        run: npm run build 