name: Keep Backend Service1 Active

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -f ${{ secrets.RENDER_BACKEND_URL1 }}/health
